### ISSUE TITLE
scripts rename-pkg does not work

### ISSUE THREAD

**Issue by GAVProject** [huangmingfu/vue3-turbo-component-lib-template#1]
```bash
pnpm run rename-pkg  @mylib @g-vue-lib

> vue3-component-lib-template@1.0.0 rename-pkg /***
> bash ./scripts/rename-package.sh "@mylib" "@g-vue-lib"

Replacing @mylib with @g-vue-lib in all files...
sed: 1: "./stylelint.config.mjs": invalid command code .
Done! Please review the changes and run 'pnpm install' to update lock file
```

**Comment by huangmingfu** [comment]
![image](https://github.com/user-attachments/assets/e814e0c4-c270-4620-93a1-2bb14b236501)
你看看git代码变动记录？应该是有改成功的，执行完命令后，需要 pnpm install 一下

**Comment by huangmingfu** [comment]
我这边测试没问题
![image](https://github.com/user-attachments/assets/314f0c56-4d3d-4f79-9792-7ca12979e458)

**Comment by moka-erb** [comment]
在mac下 sed 命令就是有问题。
sed: 1: "./stylelint.config.mjs": invalid command code .

改成下面就可以了
#!/bin/bash

# 批量替换包名脚本
# 使用：pnpm run rename-pkg old-name new-name
# 示例：pnpm rename-pkg "@mylib" "@vue3-lib"

# 参数检查
if [ "$#" -ne 2 ]; then
  echo "Usage: $0 old-name new-name"
  echo "Example: $0 @mylib @vue3-lib"
  exit 1
fi

OLD_NAME="$1"
NEW_NAME="$2"

# 转义特殊字符（/、@、&）
escape_string() {
  printf '%s' "$1" | sed -e 's/[\/&]/\\&/g' -e 's/@/\\@/g'
}

OLD_NAME_ESCAPED=$(escape_string "$OLD_NAME")
NEW_NAME_ESCAPED=$(escape_string "$NEW_NAME")

echo "Replacing $OLD_NAME with $NEW_NAME in all files..."
echo "DEBUG: Original OLD_NAME: '$OLD_NAME'"
echo "DEBUG: Escaped OLD_NAME for sed: '$OLD_NAME_ESCAPED'"
echo "DEBUG: Original NEW_NAME: '$NEW_NAME'"
echo "DEBUG: Escaped NEW_NAME for sed: '$NEW_NAME_ESCAPED'"

# 查找并替换文件内容（带备份）
find . -type f \
  -not -path "*/node_modules/*" \
  -not -path "*/dist/*" \
  -not -path "*/.git/*" \
  -not -path "*/coverage/*" \
  -not -path "*/scripts/*" \
  -not -path "*/temp/*" \
  -not -path "*/tmp/*" \
  -not -path "*/.turbo/*" \
  -not -path "*/.cache/*" \
  \( -name "*.json" -o -name "*.ts" -o -name "*.js" -o -name "*.vue" -o -name "*.md" -o -name "*.mjs" \) \
  -exec sed -i.bak "s/$OLD_NAME_ESCAPED/$NEW_NAME_ESCAPED/g" "{}" +

# 删除 .bak 备份文件
find . -type f -name "*.bak" -delete

# 显示被修改的文件（含新包名）
echo "Files updated with new package name ($NEW_NAME):"
find . -type f \
  -not -path "*/node_modules/*" \
  -not -path "*/dist/*" \
  -not -path "*/.git/*" \
  -not -path "*/coverage/*" \
  -not -path "*/scripts/*" \
  -not -path "*/temp/*" \
  -not -path "*/tmp/*" \
  -not -path "*/.turbo/*" \
  -not -path "*/.cache/*" \
  \( -name "*.json" -o -name "*.ts" -o -name "*.js" -o -name "*.vue" -o -name "*.md" -o -name "*.mjs" \) \
  -exec grep -l "$NEW_NAME" "{}" +

echo "Done! Please review the changes and run 'pnpm install' to update your lockfile."
